# Generated by Django 5.1.1 on 2024-11-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='country_name',
        ),
    ]
