# Generated by Django 5.1.1 on 2024-11-24 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=155, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='house_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='location',
            name='post_code',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{0,6}$', 'Invalid postal code')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=155, verbose_name='Street name'),
        ),
    ]
