# Generated by Django 5.1.1 on 2024-11-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_rename_country_location_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country_name',
            new_name='country',
        ),
    ]
