# Generated by Django 5.1.1 on 2024-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_rename_country_name_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
