# Generated by Django 5.1.1 on 2024-11-17 00:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_placement_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_location', to='placement.placement', verbose_name='placement'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='description',
            field=models.TextField(max_length=350, validators=[django.core.validators.MinLengthValidator(40)], verbose_name='Apartments description'),
        ),
    ]
