# Generated by Django 5.1.1 on 2024-11-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='user',
            name='is_landlord',
            field=models.BooleanField(default=False, verbose_name='Is landlord'),
        ),
    ]
