# Generated by Django 5.1.1 on 2024-11-25 22:46

import booking_project.users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to=booking_project.users.models.user.User.upload_to, verbose_name='Profile foto'),
        ),
    ]
