# Generated by Django 5.1.1 on 2024-10-29 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='apartment_area',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(10)], verbose_name='Area of apartment'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='double_bed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)], verbose_name='number of double bed'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='post_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{0,6}$', 'Invalid postal code')]),
        ),
    ]
