# Generated by Django 5.1.1 on 2024-11-18 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_info', '0001_initial'),
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Placement', to='placement.placement'),
        ),
    ]
