# Generated by Django 5.1.1 on 2024-11-13 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_info', '0001_initial'),
        ('placement', '0005_placement_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Placement', to='placement.placement'),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
